In [ ]:
import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt
import os
import tensorflow as tf

[]

In [ ]:

def generate_fpga_style_spectrogram(file_path):
    # 1. MIMII SR is 16kHz
    y, sr = librosa.load(file_path, sr=16000)
    
    # Spectrogram params optimized for Artix-7 35T
    n_fft = 1024
    hop_length = 512
    n_mels = 64
    
    # Using energy instead of power to avoid doing a square root on FPGA
    S = librosa.feature.melspectrogram(y=y, sr=sr, n_fft=n_fft, 
                                      hop_length=hop_length, 
                                      n_mels=n_mels, power=1)
    
    # Log scale for dynamic range compression
    S_log = librosa.amplitude_to_db(S, ref=np.max)
    
    # Normalization (0 to 1 for the Neural Network)
    S_norm = (S_log - np.min(S_log)) / (np.max(S_log) - np.min(S_log))
    
    return S_norm

In [ ]:
# spec = generate_fpga_style_spectrogram('../-6_dB_slider/slider/id_00/normal/00000000.wav')
# print(f"Spectrogram Shape: {spec.shape}")
# np.save('../data/spectrogram/normal/fpga_style_spectrogram.npy', spec)
# data = np.load('../data/spectrogram/normal/fpga_style_spectrogram.npy')

Spectrogram Shape: (64, 313)
[[0.9181551  0.8721758  0.87449825 ... 0.8482955  0.78587556 0.85977113]
 [0.9016505  0.83018464 0.82373637 ... 0.7797536  0.78059083 0.8503267 ]
 [0.8445646  0.8383729  0.7760005  ... 0.80505663 0.91677797 0.8561597 ]
 ...
 [0.22443669 0.08391875 0.14888778 ... 0.1068015  0.07970871 0.14375399]
 [0.21051125 0.09294356 0.1353694  ... 0.10146677 0.07632172 0.11261249]
 [0.1941023  0.09890246 0.106805   ... 0.06296249 0.05838826 0.13194245]]


In [ ]:
# files = os.listdir('../-6_dB_slider/slider/id_00/normal/')
# for i in range(len(files)):
#     file_path = os.path.join('../-6_dB_slider/slider/id_00/normal/', files[i])
#     spec = generate_fpga_style_spectrogram(file_path)
#     np.save(f'../data/spectrogram/normal/spectrogram_{i}.npy', spec)
#     if i % 10 == 0:
#         print(f"Processed {i+1}/{len(files)} files")

Processed 1/1068 files
Processed 11/1068 files
Processed 21/1068 files
Processed 31/1068 files
Processed 41/1068 files
Processed 51/1068 files
Processed 61/1068 files
Processed 71/1068 files
Processed 81/1068 files
Processed 91/1068 files
Processed 101/1068 files
Processed 111/1068 files
Processed 121/1068 files
Processed 131/1068 files
Processed 141/1068 files
Processed 151/1068 files
Processed 161/1068 files
Processed 171/1068 files
Processed 181/1068 files
Processed 191/1068 files
Processed 201/1068 files
Processed 211/1068 files
Processed 221/1068 files
Processed 231/1068 files
Processed 241/1068 files
Processed 251/1068 files
Processed 261/1068 files
Processed 271/1068 files
Processed 281/1068 files
Processed 291/1068 files
Processed 301/1068 files
Processed 311/1068 files
Processed 321/1068 files
Processed 331/1068 files
Processed 341/1068 files
Processed 351/1068 files
Processed 361/1068 files
Processed 371/1068 files
Processed 381/1068 files
Processed 391/1068 files
Processed 4

In [ ]:
# # Now lets try running inference
# model = tf.keras.models.load_model('3d_printer_anomaly_model.keras')
# test_spectrogram = generate_fpga_style_spectrogram('../-6_dB_slider/slider/id_00/abnormal/00000000.wav')
# print(f"Test Spectrogram Shape: {test_spectrogram.shape}")

Test Spectrogram Shape: (64, 313)
